version: '3.7'
services:
  dev:
    image: geiser/r-studio:latest
    container_name: 2020-CIEB-questionnaire-validation
    restart: unless-stopped
    tty: true
    volumes:
      - ./:/home/gcc 
    ports:
      - "8686:8787"
